imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, src/Controller/SessionController.php,
    src/Controller/DiceGameController.php, src/Controller/Lucky.php,
    src/Controller/ReportTwig.php, src/Controller/LibraryController.php, src/Controller/Game21.php,
    src/Controller/CardGame.php, src/Repository/BooksRepository.php, src/Repository/ProductRepository.php,
    src/Controller/MetricsController.php, src/Entity/Product.php, src/Card/DeckTask.php,
    src/Card/Game21Draw.php, src/Dice/DiceGameTask.php, src/Entity/Books.php, src/Dice/DiceHand.php,
    src/Card/Player.php]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                    # version: 8.1.13
                    # version: 8.1.17
                    # version: 8.2.4
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file
    tests:
        override:
            -   command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
